### ISSUE TITLE
如何保证续租一定成功的呢？

### ISSUE THREAD

**Issue by Yaccc** [baidu/dlock#1]
rt

**Comment by baozhi** [comment]
续租操作依赖于Redis、网络情况，无法保证续约一定成功；
DLock通过提前续约、续约失败重试等方式，配合合理的LeasTime设置，尽可能保证续约成功

**Comment by Yaccc** [comment]
redis实现分布式锁问题还是太多，thx

**Comment by baozhi** [comment]
恩，基于redis的分布式锁，更适用于可以快速试锁的场景；
如对一致性有严格的要求，可以考虑基于强一致性算法的分布式锁

**Comment by Yaccc** [comment]
zk实现分布式锁还是得牺牲一定的可用性才能保证锁的正确性。确实没有很完美的方案
