### ISSUE TITLE
为什么在取得锁的时候要定期去跑延长租约的线程

### ISSUE THREAD

**Issue by jiangzhifei** [baidu/dlock#2]
为什么在取得锁的时候要定期去跑延长租约的线程，不是很理解其中的原因。

**Comment by baozhi** [comment]
举个例子，业务逻辑处理需要10分钟，锁租约为1分钟。那么租约内肯定处理不完业务，所以需要定期续约，保证最终可以完成业务逻辑。
如果不设置租约，锁将不会自动过期，如果业务处理hang住，锁将永久无法释放。基于租约的锁机制，就是为了解决锁死的问题。

**Comment by jiangzhifei** [comment]
设置锁的有效时间不是应该业务自己应该关心的吗？业务线程在取得锁的同时设置一个超时时间。
通过不断刷新一个较短的租约这种方式，由于存在续租失败的可能性反而减低了锁的有效性。

**Comment by baozhi** [comment]
> 通过不断刷新一个较短的租约这种方式，由于存在续租失败的可能性反而减低了锁的有效性。

租约时长、续约频率可以配置，需要视业务情况而定；未设置才会用默认值
<br>

> 设置锁的有效时间不是应该业务自己应该关心的吗？业务线程在取得锁的同时设置一个超时时间。

对，不管是租约、还是固定超时时间，这个有效期都需要业务决定。
固定超时时间如何确定，往往取决于经验值，某些场景下置信度不高。比如每晚进行批处理，经验上会处理1小时，但随着数据增长、外部服务延时增长，实际处理时长可能翻倍；反观租约机制，自动续约直到完成，具备自适应处理的能力

**Comment by jiangzhifei** [comment]
如果业务在取得锁的时候设置一个较长的时间（事实上这个时间的预估准确率应该要高于续约的成功率，毕竟只管设置足够长而已），在结束的时候释放该锁，这样的处理方法是有什么问题而使得作者选择刷新续约的方式在保证持有锁？

**Comment by baozhi** [comment]
> 如果业务在取得锁的时候设置一个较长的时间

锁有效期设置过短，任务处理不完；设置过长，任务出错时，锁不能及时得到释放，影响正常业务。lease机制，自动续约就没有上述问题。
租约机制，在分布式系统中，会对容错性有一定保证。这是常规超时时间所不具备的

**Comment by jiangzhifei** [comment]
谢谢
